name: Linter
run-name: $ {{ github.actor }} / $ {{ github.workflow }} / $ {{ github.run_number }}
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: run Linter
        run: npm run lint
